### ISSUE TITLE
Hey  Purnima have you fixed the submitbutton issue i donot know why it's not working ? Can you please help me out with it

### ISSUE THREAD

**Issue by Samm0707** [Purnima-Vats/carepulse#1]

**Comment by Purnima-Vats** [comment]
which submit button? Can you elaborate? all buttons are working now in the repo.

**Comment by Samm0707** [comment]
hey Purnima , related submit & Continue button while filling all the details
![Screenshot 2024-08-24 224420](https://github.com/user-attachments/assets/b1b42ce8-e6fd-4d17-a2f0-610ea47d428d)
This one can you please help me out on this !

**Comment by Samm0707** [comment]
I'm just stuck on this from the last week Please please help me out on this

**Comment by Purnima-Vats** [comment]
Can you give me your repo so I can run it on my computer and tell you exactly what the issue is?
as I can see in the screenshot, there is no clear error about why submit is not working.

**Comment by Samm0707** [comment]
That would be great 😃

**Comment by Samm0707** [comment]
https://github.com/Shivamkainthola07/MediMitra

**Comment by Samm0707** [comment]
Please update with the errors in my Repo

**Comment by Samm0707** [comment]
@Purnima-Vats can you please share your Appwrite screenshots as I may see changes there and then I can run your Repo ...
